package com.ass.common;

public enum PageType {
		USER_MANAGEMENT_PAGE,
		ORDER_MANAGEMENT_PAGE,
		PRODUCT_MANAGEMENT_PAGE,
		ADMINISTRATION_PAGE,
		SITE_HOMEPAGE,
		SITE_LOGINPAGE,
		SITE_REGISTRATIONPAGE,
		SITE_CHANGEPASSWORDPAGE,
		SITE_FORGOTPASSWORDPAGE,	
		SITE_EDITPROFILEPAGE,
		SITE_CARTPAGE
		
}
